jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_KEY_PW: ${{ secrets.GPG_SIGNING_KEY_PW }}
      if: github.repository == 'KeepSafe/dexcount-gradle-plugin' && github.ref ==
        'refs/heads/master'
      name: Import snapshot GPG key
      run: 'echo "$GPG_SIGNING_KEY_PW" | gpg --batch --import --yes --passphrase-fd
        0 <(echo -n "$GPG_SIGNING_KEY" | base64 --decode)

        mkdir -p ~/.gradle

        echo -n "signing.gnupg.passphrase=${GPG_SIGNING_KEY_PW}" >> ~/.gradle/gradle.properties

        '
    - continue-on-error: true
      if: github.repository != 'KeepSafe/dexcount-gradle-plugin' || github.ref !=
        'refs/heads/master'
      name: Import random GPG key
      run: "gpg --batch --gen-key <(cat <<EOF\n  Key-Type: 1\n  Key-Length: 2048\n\
        \  Key-Usage: sign\n  Passphrase: foobar\n  Name-Real: Dexcount Developers\n\
        \  Name-Email: foo@bar.com\n  Expire-Date: seconds=1200\n  %commit\nEOF\n\
        )\nmkdir -p ~/.gradle\necho -n \"signing.gnupg.passphrase=foobar\" >> ~/.gradle/gradle.properties\n"
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Cache Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build and test
      run: ./gradlew check
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD
          }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME
          }}
      if: github.event_name == 'push' && github.repository == 'KeepSafe/dexcount-gradle-plugin'
        && github.ref == 'refs/heads/master'
      name: Deploy snapshot
      run: ./gradlew uploadSnapshot
    strategy:
      matrix:
        jdk:
        - 17
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
